### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by APJifengc** [Yallage/YaInject#1]
5Y+R5Y+q5piv5oiR55yf55qE5rKh5pyJ5Yir55qE5Yqe5rOV6IGU57O75LqG77yJ77yJCmh0dHBzOi8vaGFjay5jaGF0Lz9hcGotY2hhdArvvInvvIkK

**Comment by milkory** [comment]
这是什么仓？？

**Comment by APJifengc** [comment]
aHR0cHM6Ly9iZXRhLmhhY2suY2hhdC8/YXBqLWNoYXQKYiBlIHQgYQo=

**Comment by milkory** [comment]
nm**l，不能明文说话？

**Comment by milkory** [comment]
犽谷复活了，这非常好

**Comment by APJifengc** [comment]
不能

**Comment by APJifengc** [comment]
我突然又能上github了
太神奇了

**Comment by APJifengc** [comment]
悠悠来学习组合数
https://apjifengc.blog.luogu.org/post-xue-xi-bi-ji-qiu-zu-ge-shuo-fang-fa-tai-quan

**Comment by APJifengc** [comment]
https://github.com/APJifengc/apj-cpp-codes
apj把他写的代码上传了
顺便apj搭了一个博客））
http://apjifengc.gitee.io/
（apj在没有git的情况下用gitee的web ide与remote，fork，上传文件艰难的搭建的

**Comment by APJifengc** [comment]
https://github.com/Oceanik-Lib/oceaniko-idea/blob/7072411967166ccd4c454e4e26373756cba0a7da/src/main/java/com/yallage/oceanik/idea/util/CustomFileTemplateManager.java#L59
真就O(n^2)匹配呗 寒冰你不会写这种东西的吧 不会吧不会吧（跑
@hanbings

**Comment by APJifengc** [comment]
（虽然我还没字符串匹配 跑

**Comment by APJifengc** [comment]
https://github.com/Oceanik-Lib/oceaniko-idea/blob/7072411967166ccd4c454e4e26373756cba0a7da/src/main/java/com/yallage/oceanik/idea/util/CustomFileTemplateManager.java#L34
保 持 数 据 原 汁 原 味

**Comment by APJifengc** [comment]
话说github不是有一个discussion功能吗（或者说被砍了我不知道
我在issue里聊天是不是不太好

**Comment by APJifengc** [comment]
a p j - e m a i l 爆 破 器 2 0 0 0

**Comment by hanbings** [comment]
草 我抄的java.lang.String#replace的 要是不考虑转String会丢失换行符 我还想倒腾成String完事之后再转回来

**Comment by hanbings** [comment]
这两天在fabric那边摸鱼 摸炸了 刚刚因为一个null失礼回来 https://github.com/FabricMC/fabric-loom/pull/439

**Comment by APJifengc** [comment]
话说loader类和bukkit主类是不是应该隐藏起来） gradle编译的时候自动打包进去
我翻oceanik代码时候反正是这么想的

**Comment by APJifengc** [comment]
> 草 我抄的java.lang.String#replace的 要是不考虑转String会丢失换行符 我还想倒腾成String完事之后再转回来

那没事了 跑）

**Comment by hanbings** [comment]
丢人丢人丢人 https://github.com/hanbings/fabric-loom-cn/commit/8d2aabeb0a477fc34414eba6560e16169eae80a4

**Comment by APJifengc** [comment]
> 这两天在fabric那边摸鱼 摸炸了 刚刚因为一个null失礼回来 [FabricMC/fabric-loom#439](https://github.com/FabricMC/fabric-loom/pull/439)

草

**Comment by APJifengc** [comment]
xs

**Comment by APJifengc** [comment]
悠悠要骂人了

**Comment by APJifengc** [comment]
h a n b i n g s - a p j - e m a i l - 爆 破 器 v 2 . 0

**Comment by APJifengc** [comment]
@milkory 快去写gradle插件

**Comment by milkory** [comment]
草
